apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadsrkx2032-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadsrkx2032-tenant-component
    app.kubernetes.io/part-of: loadsrkx2032-tenant-app
  name: loadsrkx2032-tenant-component
  namespace: loadsrkx2032-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadsrkx2032-tenant-component
    weight: null
status: {}
